# docker-compose.prod.yml
version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:13-alpine
    container_name: video-tracker-postgres
    restart: always
    environment:
      POSTGRES_USER: ${PGUSER:-postgres}
      POSTGRES_PASSWORD: ${PGPASSWORD:-postgres}
      POSTGRES_DB: ${PGDATABASE:-video_progress_tracker}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - app-network

  # Backend Node.js API
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: video-tracker-backend
    restart: always
    environment:
      NODE_ENV: production
      PORT: 5000
      PGHOST: postgres
      PGUSER: ${PGUSER:-postgres}
      PGDATABASE: ${PGDATABASE:-video_progress_tracker}
      PGPASSWORD: ${PGPASSWORD:-postgres}
      PGPORT: 5432
      JWT_SECRET: ${JWT_SECRET:-uWxz9Kq7BpTfA5mJ2eD8sR4vL6yH3nG1}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-1d}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-cX7bN2pE6tY9vR4zK3mS8wQ1aD5gF0jH}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN:-7d}
      CLIENT_URL: http://localhost
    depends_on:
      - postgres
    networks:
      - app-network

  # Frontend React Application
  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: video-tracker-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

# Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  postgres_data:
    driver: local
