[build]
  base = "client"
  command = "npm run build"
  publish = "client/build"

[build.environment]
  CI = "false"

# Optional: if you want to use Netlify Functions
# [functions]
#   directory = "client/netlify/functions"
